name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        submodules: "recursive"
        fetch-depth: 0

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
      
    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh
      
    - name: Upload SafetyNetFix.zip
      uses: actions/upload-artifact@v3
      with:
        name: SafetyNetFix
        path: safetynet-fix-*.zip
